# To use:
#   $ conda env create -f environment.yml
#   $ conda activate VizCalibrateEDMF

name: VizCalibrateEDMF
channels:
  - conda-forge
dependencies:
  - python=3.9 
  - pandas
  - seaborn
  - setuptools
  - scipy
  - scipy
  - matplotlib
  - netcdf4
  - numpy
  - xarray
